#ifndef CUSTOMPLUGINPLUGINLIB_GLOBAL_H
#define CUSTOMPLUGINPLUGINLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOMPLUGIN_LIBRARY)
#  define CUSTOMPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOMPLUGIN_EXPORT Q_DECL_IMPORT
#endif


#endif // CUSTOMPLUGINPLUGINLIB_GLOBAL_H
