#ifndef SKIFDIAGNOSTICPLUGINLIB_GLOBAL_H
#define SKIFDIAGNOSTICPLUGINLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SKIFDIAGNOSTICPLUGIN_LIBRARY)
#  define SKIFDIAGNOSTICPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SKIFDIAGNOSTICPLUGIN_EXPORT Q_DECL_IMPORT
#endif


#endif // SKIFDIAGNOSTICPLUGINLIB_GLOBAL_H
