#ifndef COMMONINTERFACES_GLOBAL_H
#define COMMONINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONINTERFACES_LIBRARY)
#  define COMMONINTERFACES_EXPORT Q_DECL_EXPORT
#else
#  define COMMONINTERFACES_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONINTERFACES_GLOBAL_H
