name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v.2.0.0
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.7.2
      with:
        submodule_update: ON
        run_tests: ON
