name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: '5.12.9'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/example/'
        install-deps: 'true'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        aqtversion: '==0.9'
        py7zrversion: '==0.7'
        extra: '--external 7z'
    - run: ls
    - run: pwd
    - run: cd VirtusProxyGUI
    - run: ls
    - run: qmake "CONFIG+=VirtusProxyGUI" ./VirtusProxyGUI/VirtusProxyGUI.pro
    - run: make
