name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.7.2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
